### ISSUE TITLE
GlueControlManager.Generated.cs fails to compile against released FlatRedBall NuGet packages (ScreenLoadExceptionOccurred)

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#2255]
PR #2254 added `ScreenManager.ScreenLoadExceptionOccurred` and referenced it unconditionally from the embedded `GlueControlManager.cs` template. Any game project that references FlatRedBall via a released NuGet package (rather than engine source) fails to compile with:

```
GlueControl\GlueControlManager.Generated.cs(161,47): error CS0117: 'ScreenManager' does not contain a definition for 'ScreenLoadExceptionOccurred'
```

Confirmed via CI on #2254 itself (failed, merged anyway) and inherited by #2253's CI run. `EditorTest1` (used by `LiveGameProcessTests`) references FlatRedBall via `PackageReference`, not source, and its pinned package predates this member.

Needs the standard retroactive version-gating per the `gluj-versions` skill: a new `GluxVersions` entry at the same integer value as the most recent shipped version, and `#if SymbolName || REFERENCES_FRB_SOURCE` around the new usage in `GlueControlManager.cs`.
